from pathlib import Path


def write_markdown_report(
    output_dir: Path,
    chapter: dict,
    llm: dict,
    overall: float,
    analysis: dict,
    structure: dict,
    today: str,
) -> Path:
    chapter_id = chapter["chapter_id"]
    safe_id = chapter_id.replace("/", "_")
    outfile = output_dir / f"{today}_{safe_id}_review.md"

    critique = analysis.get("critique", {})
    editorial = analysis.get("editorial", {})

    issues_md = ""
    for i, issue in enumerate(critique.get("issues", []), 1):
      issues_md += (
          f"\n### {i}. {issue.get('name', 'Issue')} *[{issue.get('lens', '')}]*\n\n"
          f"**Problem**: {issue.get('problem', '—')}\n\n"
          f"**Why it matters**: {issue.get('why_it_matters', '—')}\n\n"
          f"**Fix**: {issue.get('fix', '—')}\n"
      )

    priorities_md = "\n".join(
      f"{i}. {p}" for i, p in enumerate(editorial.get("priorities", []), 1)
    ) or "None identified."

    flags = editorial.get("flags", [])
    flags_md = (
      "\n| Phrase | Type | Action |\n|--------|------|--------|\n"
      + "\n".join(
          f"| `{f.get('phrase','')}` | {f.get('type','')} | {f.get('action','')} |"
          for f in flags
      )
    ) if flags else "No specific flags."

    must_fix_md = "\n".join(f"- {i}" for i in structure.get("must_fix", [])) or "None."
    should_fix_md = "\n".join(f"- {i}" for i in structure.get("should_fix", [])) or "None."

    content = f"""\
# Book Review: {chapter['title']}

**Book**: {chapter['book_title']}
**Chapter**: `{chapter_id}` (#{chapter['chapter_num']})
**Date**: {today}
**Overall Score**: {overall} / 5.0  *(flagged: overall<3.0 or any dim<=2)*
**Scores**: arc={llm.get('narrative_arc',0)} · arg={llm.get('argument_quality',0)} · clarity={llm.get('clarity',0)} · signal={llm.get('signal_ratio',0)} · structure={chapter.get('structure_score',0)}

---

## Critique

**Chapter thesis**: {critique.get('chapter_thesis', '—')}

**Core gap**: {critique.get('core_gap', '—')}

**Altitude note**: {critique.get('altitude_note', '—')}

### Priority Issues
{issues_md}
**If you fix one thing**: {critique.get('one_fix', '—')}

---

## Editorial Review

| Dimension | Rating |
|-----------|--------|
| Structural Integrity | {editorial.get('structural_integrity', '—')} |
| Argument Quality | {editorial.get('argument_quality', '—')} |
| Clarity | {editorial.get('clarity', '—')} |
| Signal Ratio | {editorial.get('signal_ratio', '—')} |
| **Overall** | **{editorial.get('overall', '—')}** |

### Priorities

{priorities_md}

### Voice Flags

{flags_md}

---

## Structure Report *(rule-based)*

| Category | Value |
|----------|-------|
| Structure Score | {structure.get('structure_score', '—')} / 5 |
| Word Count | {structure.get('word_count', 0)} |
| Rating | {structure.get('structure_rating', '—')} |
| Has Key Takeaways | {'Yes ⚠' if structure.get('has_key_takeaways') else 'No'} |
| Has Intro Box | {'Yes ⚠' if structure.get('has_chapter_intro_box') else 'No'} |
| Passive Conclusion | {'Yes ⚠' if structure.get('has_passive_conclusion') else 'No'} |

### Must Fix

{must_fix_md}

### Should Fix

{should_fix_md}

---

*Generated by remediate_chapters.py · {today}*
"""
    outfile.write_text(content, encoding="utf-8")
    return outfile
